### PR TITLE
display help page on unknown commands

### PR DESCRIPTION
**Pull request by stephchen-stripe**
### Reviewers
r? @ob-stripe 
cc @stripe/dev-platform

 ### Summary
show help page when `stripe` receives an unknown command

### CODE REVIEW

**Comment by ob-stripe** [comment]
This works, but I'm worried the output is too verbose since the help is so long. Maybe we should do something similar to `git`:

```sh
$ git checkot
git: 'checkot' is not a git command. See 'git --help'.

The most similar command is
	checkout
```

@tomer-stripe wdyt?

**Comment by stephchen-stripe** [comment]
@ob-stripe so we have the "closest match" correction enabled just as with git although the edit distance is currently set to 2 (so it doesn't catch "configure" => "config" as in the original ticket). we could just adjust the current error message to tell the user to go to "--help" (it currently doesn't) instead of displaying the whole help page

**Comment by ob-stripe** [comment]
> we could just adjust the current error message to tell the user to go to "--help" (it currently doesn't) instead of displaying the whole help page

Yes, that's what I meant. It shouldn't be too hard to catch the "unknown command" error as you're currently doing and then reconstructing our own customized error message using the same functions as cobra itself: https://github.com/spf13/cobra/blob/f619abc1d7edb30544d1c956719d203ace73e9b1/args.go#L21

**Comment by stephchen-stripe** [comment]
flow now looks like this:
```
st-stephchen1:stripe-cli stephchen$ stripe-dev configu
Unknown command "configu" for "stripe". Did you mean "config"?
If not, see "stripe --help" for a list of available commands.
```

**Comment by stephchen-stripe** [comment]
flow now looks like this
```
st-stephchen1:stripe-cli stephchen$ stripe-dev configu
Unknown command "configu" for "stripe". Did you mean "config"?
If not, see "stripe --help" for a list of available commands.
exit status 1
st-stephchen1:stripe-cli stephchen$ stripe-dev configuasdf
Unknown command "configuasdf" for "stripe".
See "stripe --help" for a list of available commands.
exit status 1
```

**Pull request merged**
