### PR TITLE
Add Linux installation instructions to README.md, replacing Bintray r…

### PR DESCRIPTION
**Pull request by mattfox**
…epos with Balto, resolving #656 and #666.

 ### Reviewers
r? @
cc @stripe/developer-products

 ### Summary

### CODE REVIEW

**Comment by chrisdlangton** [comment]
### CAUTION TO MAINTAINERS

Ensure you do your due diligence on Balto as a trustworthy service provider.
And ensure the code contributions are _safe_ 

Software supply chain infiltration that lead to breaches, big news like NotPetya, ASUS, Solarwinds, PHP, plus the thousands of packages available through package managers that have contributes sneak in code to create backdoors and worse.

This is Stripe, a payments platform. We use you to avoid having card holder data in our organisations AND avoid the compliance requirements this arrangement enables. We put complete trust of the viability of our businesses in Stripe's ability to do basic security hygiene (software supply chain due diligence in this case).

We are not allowed to audit you an ensure you've done them, which is how we used to chose vendors for decades (until cloud scale arrived), so please show some transparency here and discuss your due diligence before what would appear as a blind merge of an opportunistic (in appearance) replacement for a service that was decommissioned by a reputable well-known company.

**Comment by mattfox** [comment]
Absolutely, supply chain trust is critical. I'd be pleased to answer any questions.

For what it's worth, Balto has hosted repos for the [Helm package manager for Kubernetes](https://helm.sh/docs/intro/install/#from-apt-debianubuntu) for about a year- not that you should trust Helm, but anyone can verify the important bits about their repo: (1) the packages available there only contain the Helm binaries and related files, (2) the Helm binaries in the packages are the same binaries offered on their Github releases page, and (3) there are no non-Helm packages in those repos.

Obviously that's only rudimentary due diligence. For some orgs it would be enough and for others it would be just a start.

**Comment by tomer-stripe** [comment]
Hey all -- appreciate this PR but we've been working on some options that align more closely with our existing build and deploy pipelines within Stripe. I'm going to close this PR and we'll keep working on a solution for our users. I'll try to post an update on this shortly!

**Comment by dotnetCarpenter** [comment]
@tomer-stripe It's now been exactly one year and the official way of installing stripe-cli is manually!

The official documentation says:
> To install the Stripe CLI on Linux without a package manager:
>
>    Download the latest linux tar.gz file from https://github.com/stripe/stripe-cli/releases/latest
>    Unzip the file: tar -xvf stripe_X.X.X_linux_x86_64.tar.gz
>    Move ./stripe to your execution path.

Perhaps it is time to take up @mattfox on his offer?

**Comment by dotnetCarpenter** [comment]
@tomer-stripe, yesterday I developed a small tool to install `stripe-cli` called [`install-stripe-cli`](https://github.com/dotnetCarpenter/dotfiles/blob/master/install-stripe-cli). See https://github.com/stripe/stripe-cli/issues/666#issuecomment-1079704202 for an introduction. ;)

_it's the number of the beast_

**Pull request closed without merging**
