### PR TITLE
Add price.created, price.deleted, and price.updated events

### PR DESCRIPTION
**Pull request by elenatorro**
### Reviewers

r? @stripe/developer-products
cc @stripe/developer-products

 ### Summary

Add price events for local testing.
Related to https://github.com/stripe/stripe-cli/issues/488 

```bash
$ stripe-dev trigger 'price.created'
$ stripe-dev trigger 'price.deleted'
$ stripe-dev trigger 'price.updated'
```

### CODE REVIEW

**Review by gracegoo-stripe — APPROVED** [review]
LGTM!

**Comment by vcheung-stripe** [comment]
Hi @elenatorro, thanks for the PR! Unfortunately, we don’t have an API to trigger `price.deleted` via the CLI; today, prices can only be deleted in the Stripe Dashboard. Please remove `price.deleted` from this PR. The other events `price.created` and `price.updated` look good to me though!

**Comment by elenatorro** [comment]
Thanks, @vcheung-stripe! 

I didn't realize I couldn't remove a price from the API, thanks for the review 👌🏽

**Review by vcheung-stripe — APPROVED** [review]
🚀

**Pull request merged**
