### PR TITLE
Add account.updated trigger

### LINKED ISSUE #345: Support triggering account.updated event
### Problem
I'm trying to build a webhook endpoint to detect when Connect accounts reach a threshold that changes their verification requirements

### Feature
Support the account.updated event in stripe CLI

### PR DESCRIPTION
**Pull request by tomer-stripe**
### Reviewers
r? @gracegoo-stripe 
cc @stripe/developer-products @suz-stripe @pepin-stripe 

 ### Summary
Adds trigger for `account.updated`:
```
➜ stripe-dev trigger account.updated
Setting up fixture for: account
Setting up fixture for: update_account
Trigger succeeded! Check dashboard for event details.
```

```
➜ stripe listen
2021-02-05 13:00:47   --> connect person.created [evt_1IHbQ3Gipd0n7NTAdynfbI58]
2021-02-05 13:00:51   --> connect account.updated [evt_1IHbQ6Gipd0n7NTAnXuk0oFz]
```

Resolves #345

### CODE REVIEW

**Review by gracegoo-stripe — APPROVED** [review]

**Review by pepin-stripe — APPROVED** [review]
LGTM!

**Comment by Wharley01** [comment]
now getting error "event account.updated is not supported" error

**Comment by pepin-stripe** [comment]
> now getting error "event account.updated is not supported" error

Hello @Wharley01, this PR hasn't been merged and released yet, so that's expected.

**Comment by Wharley01** [comment]
> > now getting error "event account.updated is not supported" error
> 
> Hello @Wharley01, this PR hasn't been merged and released yet, so that's expected.

When is it expected to ship ?

**Comment by Wharley01** [comment]
> > now getting error "event account.updated is not supported" error
> 
> Hello @Wharley01, this PR hasn't been merged and released yet, so that's expected.

Now shipped! thanks!

**Comment by marnixhoh** [comment]
Hi just wanted to let you know (maybe this is already known/expected), that the account.updated trigger has not been added yet to the VSCode extension. Hope this helps!

**Comment by gracegoo-stripe** [comment]
> Hi just wanted to let you know (maybe this is already known/expected), that the account.updated trigger has not been added yet to the VSCode extension. Hope this helps!

Thanks for letting us know,@marnixhoh. Sorry about the delay here, I've updated the list: https://github.com/stripe/vscode-stripe/pull/218

**Pull request merged**
