### PR TITLE
Change intro wording

### PR DESCRIPTION
**Pull request by tomer-stripe**
### Reviewers
r? @ob-stripe @brandur-stripe @romain-stripe @mg-stripe 
cc @stripe/dev-platform

### CODE REVIEW

**Comment by brandur-stripe** [comment]
Seems fine to me too.

**Comment by romain-stripe** [comment]
> Easily test your webhook integration, tail your logs to monitor requests coming in, or create samples to learn about different Stripe integrations.

I'd change the wording a bit for the last part since users don't _create_ samples. Maybe something like this? Happy to give it another pass!

> Interact with any part of the API, debug your integration with real-time request logs, receive webhook events locally on your machine with a built-in proxy, and fetch samples to find building blocks for your integration.

**Comment by mg-stripe** [comment]
My suggestion:

> Use the Stripe API from the command line, debug your Stripe integration with real-time logs, forward webhook events to your local application, and quickly get started with pre-built samples (https://stripe.dev/samples).

I think we should include the link so that developers can see what Samples are, but I would be OK with excluding that.

**Comment by tomer-stripe** [comment]
Thanks all! Updating with @mg-stripe's suggestion :D

**Pull request merged**
