### PR TITLE
Refactor Profile and CLI Configuration

### PR DESCRIPTION
**Pull request by aarongreen-stripe**
### Reviewers
r? @ob-stripe  @tomer-stripe 
cc @stripe/dev-platform

 ### Summary
The existing `Profile` package had additional properties and didn't map clearly to the information stored in the profile configuration files. This change creates a more clear separation of responsibility between `Profile` and general `Config`.

`Config` is the overall configuration for the CLI and contains the active `Profile` as a property; whereas `Profile` now distinctly refers to the `DeviceName` and `SecretKey` stored in the profile configuration file.

Additionally, it renames the `profile` package to be the `config` package, more broadly encompassing configuration for the CLI.

### Motivation
[Jira Ticket](https://jira.corp.stripe.com/browse/DX-4361)

### CODE REVIEW

**Comment by tomer-stripe** [comment]
ptal @aarongreen-stripe

**Comment by aarongreen-stripe** [comment]
Addressed. ptal @tomer-stripe

**Comment by tomer-stripe** [comment]
lgtm!

**Comment by aarongreen-stripe** [comment]
lgtm

**Pull request merged**
