### PR TITLE
Upgrade to go 1.15.x and upgrade dependencies

### PR DESCRIPTION
**Pull request by tomer-stripe**
### Reviewers
r? @ob-stripe @richardm-stripe 
cc @stripe/developer-products 

 ### Summary
Upgrade go version and dependencies. goreleaser deprecated `github` in favor of `tap` (https://goreleaser.com/deprecations#brewsgithub) so I'm updating that before it breaks anything.

### CODE REVIEW

**Review by ob-stripe — COMMENTED** [review]
Leaving the final review to @richardm-stripe, but lgtm!

**Comment by tomer-stripe** [comment]
ptal @pepin-stripe 

Since you're spinning up here!

**Review by pepin-stripe — CHANGES_REQUESTED** [review]
looks good to me too - I assume most of those are automatically generated?

**Review by pepin-stripe — APPROVED** [review]
sorry meant to approve!

**Comment by tomer-stripe** [comment]
merging! changes were a rebase after merging in #503

**Pull request merged**
