### PR TITLE
Fix checkout.session.async_payments_* triggers

### PR DESCRIPTION
**Pull request by ahlee-stripe**
### Reviewers
r? @stripe/developer-products 
cc @stripe/dev-platform

 ### Summary

- Fix small string/int conversion error in pkg/fixtures
- Update `checkout.session.async_payments_failed` and `checkout.session.async_payments_succeeded` to set `"setup_future_usage": "off_session"`. This is required when creating a checkout session in payment mode for BACS direct (https://stripe.com/docs/payments/bacs-debit/accept-a-payment#create-session)

### Testing
Switched to a UK based stripe account. Ran `$ stripe-dev trigger checkout.session.async_payment_succeeded` and `$ stripe-dev trigger checkout.session.async_payment_failed` while using `stripe listen`. Confirmed that all the events came through as expected.

### CODE REVIEW

**Comment by tomer-stripe** [comment]
Thanks @ahlee-stripe! This looks good. Let me see if I can test out the fixtures version error later, that came up in my PR too (https://github.com/stripe/stripe-cli/pull/502/files#diff-133d387253cca3c9f0d5be8b5c845987) and I'm wondering if there's a difference (or if we care) about rendering it as a decimal.

**Comment by ahlee-stripe** [comment]
@tomer-stripe If you want I can pull out the fixtures error fix so more testing can happen on it

**Comment by tomer-stripe** [comment]
@ahlee-stripe yea that would be great, ty!

**Comment by ahlee-stripe** [comment]
@tomer-stripe Done! Removed the conversion fix.

**Pull request merged**
